const express = require('express')
const router = express.Router()
const userRoutes = require('./user.route')
const productRoutes = require('./product.route')
const cartRoutes = require('./cart.route')
const checkoutRoutes = require('./checkout.route')
const adminRoutes = require('./admin.route')
router.use('/', userRoutes)
router.use('/admin',adminRoutes)
router.use('/product', productRoutes)
router.use('/cart', cartRoutes)
router.use('/checkout', checkoutRoutes)
module.exports = router