const express = require('express')
const router = express.Router()
const userRoutes = require('./user.route')
const productRoutes = require('./product.route')
const cartRoutes = require('./cart.route')
const checkoutRoutes = require('./checkout.route')
const adminRoutes = require('./admin.route')
const categoryRoutes = require('./category.route')
const subcategoryRoutes = require('./subcategory.route')
router.use('/user', userRoutes)
router.use('/admin', adminRoutes)
router.use('/products', productRoutes)
router.use('/categories', categoryRoutes)
router.use('/subcategories', subcategoryRoutes)
router.use('/cart', cartRoutes)
router.use('/checkout', checkoutRoutes)
module.exports = router